Import('*')

import pandas as pd
df = pd.read_csv('replication/dispatch.csv')
papers = [row['paper'] for _, row in df.iterrows() if row['num_blocks'] > 0]
for paper in papers:
    num_blocks = df[df['paper'] == paper]['num_blocks'].values[0]
    num_reps = df[df['paper'] == paper]['reps_per_block'].values[0]

    target = [f'#temp/replication/{paper}/sconscript.log']
    source = ['#source/derived/replication/prep_randomization.py']
    env.Python(target, source, CL_ARG=f'{paper}')

    for block_num in range(num_blocks):
        target = [f'#temp/replication/{paper}/block_{block_num}/sconscript.log']
        source = ['#source/derived/replication/run_randomization.py',
                  f'#temp/replication/{paper}/sconscript.log']
        env.Python(target, source, CL_ARG=f'{paper} {block_num} {num_reps}')
    
    target = [f'#temp/replication/{paper}/output_{paper}.csv']
    source = ['#source/derived/replication/process_results.py']
    source += [f'#temp/replication/{paper}/block_{block_num}/sconscript.log' for block_num in range(num_blocks)]
    env.Python(target, source, CL_ARG=paper)

target = ['#output/derived/replication/sconscript.log']
source = ['#source/derived/replication/combine_outputs.py']
source += [f'#temp/replication/{paper}/output_{paper}.csv' for paper in papers]
env.Python(target, source)
